<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Kvantitative metoder for de finansielle uddannelser.</title>
  <meta name="description" content="Kvantitative metoder.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Kvantitative metoder for de finansielle uddannelser." />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Kvantitative metoder." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Kvantitative metoder for de finansielle uddannelser." />
  
  <meta name="twitter:description" content="Kvantitative metoder." />
  

<meta name="author" content="Thomas Petersen">


<meta name="date" content="2018-09-28">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
<link rel="prev" href="cran-r.html">
<link rel="next" href="klyngeanalyse.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistik</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="1" data-path="sandsynligheder.html"><a href="sandsynligheder.html"><i class="fa fa-check"></i><b>1</b> Sandsynligheder</a><ul>
<li class="chapter" data-level="1.0.1" data-path="sandsynligheder.html"><a href="sandsynligheder.html#forenings--og-flleshndelser"><i class="fa fa-check"></i><b>1.0.1</b> Forenings- og fælleshændelser</a></li>
<li class="chapter" data-level="1.1" data-path="sandsynligheder.html"><a href="sandsynligheder.html#betingede-sandsynligheder"><i class="fa fa-check"></i><b>1.1</b> Betingede sandsynligheder</a><ul>
<li class="chapter" data-level="1.1.1" data-path="sandsynligheder.html"><a href="sandsynligheder.html#race-og-ddsdom-eksempel"><i class="fa fa-check"></i><b>1.1.1</b> Race og dødsdom eksempel</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="sandsynligheder.html"><a href="sandsynligheder.html#uafhngighed"><i class="fa fa-check"></i><b>1.2</b> Uafhængighed</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chi-i-anden-tests.html"><a href="chi-i-anden-tests.html"><i class="fa fa-check"></i><b>2</b> Chi i anden tests</a><ul>
<li class="chapter" data-level="2.1" data-path="chi-i-anden-tests.html"><a href="chi-i-anden-tests.html#goodness-of-fit-test"><i class="fa fa-check"></i><b>2.1</b> Goodness of fit test</a></li>
<li class="chapter" data-level="2.2" data-path="chi-i-anden-tests.html"><a href="chi-i-anden-tests.html#forudstning"><i class="fa fa-check"></i><b>2.2</b> Forudsætning</a></li>
<li class="chapter" data-level="2.3" data-path="chi-i-anden-tests.html"><a href="chi-i-anden-tests.html#chi-i-anden-test"><i class="fa fa-check"></i><b>2.3</b> Chi i anden test</a></li>
<li class="chapter" data-level="2.4" data-path="chi-i-anden-tests.html"><a href="chi-i-anden-tests.html#chi-i-anden-test-2"><i class="fa fa-check"></i><b>2.4</b> Chi i anden test 2</a><ul>
<li class="chapter" data-level="2.4.1" data-path="chi-i-anden-tests.html"><a href="chi-i-anden-tests.html#uafhngighed-1"><i class="fa fa-check"></i><b>2.4.1</b> Uafhængighed</a></li>
<li class="chapter" data-level="2.4.2" data-path="chi-i-anden-tests.html"><a href="chi-i-anden-tests.html#anmeldte-skader-fordelt-pa-regioner-og-antal-skader"><i class="fa fa-check"></i><b>2.4.2</b> Anmeldte skader fordelt på regioner og antal skader</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chi-i-anden-tests.html"><a href="chi-i-anden-tests.html#selvtest"><i class="fa fa-check"></i><b>2.5</b> Selvtest</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>3</b> ANOVA</a><ul>
<li class="chapter" data-level="3.1" data-path="anova.html"><a href="anova.html#selvtest-1"><i class="fa fa-check"></i><b>3.1</b> Selvtest</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="cran-r.html"><a href="cran-r.html"><i class="fa fa-check"></i><b>4</b> Cran R</a><ul>
<li class="chapter" data-level="4.1" data-path="cran-r.html"><a href="cran-r.html#r-video-tutorials"><i class="fa fa-check"></i><b>4.1</b> R video-tutorials</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="faktoranalyse.html"><a href="faktoranalyse.html"><i class="fa fa-check"></i><b>5</b> Faktoranalyse</a><ul>
<li class="chapter" data-level="5.1" data-path="faktoranalyse.html"><a href="faktoranalyse.html#hvilke-faktorer-er-vigtige-nar-man-kber-en-ny-computer"><i class="fa fa-check"></i><b>5.1</b> Hvilke faktorer er vigtige når man køber en ny computer:</a></li>
<li class="chapter" data-level="5.2" data-path="faktoranalyse.html"><a href="faktoranalyse.html#forudstninger-for-faktoranalysen."><i class="fa fa-check"></i><b>5.2</b> Forudsætninger for faktoranalysen.</a></li>
<li class="chapter" data-level="5.3" data-path="faktoranalyse.html"><a href="faktoranalyse.html#selve-faktoranalysen"><i class="fa fa-check"></i><b>5.3</b> Selve Faktoranalysen</a></li>
<li class="chapter" data-level="5.4" data-path="faktoranalyse.html"><a href="faktoranalyse.html#hvor-mange-faktorer-br-benyttes"><i class="fa fa-check"></i><b>5.4</b> Hvor mange faktorer bør benyttes?</a><ul>
<li class="chapter" data-level="5.4.1" data-path="faktoranalyse.html"><a href="faktoranalyse.html#eigenvalues-metoden"><i class="fa fa-check"></i><b>5.4.1</b> Eigenvalues metoden</a></li>
<li class="chapter" data-level="5.4.2" data-path="faktoranalyse.html"><a href="faktoranalyse.html#screeplot-metoden"><i class="fa fa-check"></i><b>5.4.2</b> Screeplot metoden</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="klyngeanalyse.html"><a href="klyngeanalyse.html"><i class="fa fa-check"></i><b>6</b> Klyngeanalyse</a></li>
<li class="chapter" data-level="7" data-path="us-arrestationer-samt-urbaniseringsgrad.html"><a href="us-arrestationer-samt-urbaniseringsgrad.html"><i class="fa fa-check"></i><b>7</b> US arrestationer samt urbaniseringsgrad</a></li>
<li class="chapter" data-level="8" data-path="kvantitative-metoder.html"><a href="kvantitative-metoder.html"><i class="fa fa-check"></i><b>8</b> Kvantitative metoder</a></li>
<li class="chapter" data-level="9" data-path="arima000.html"><a href="arima000.html"><i class="fa fa-check"></i><b>9</b> ARIMA(0,0,0)</a></li>
<li class="chapter" data-level="10" data-path="arima100-eller-ar1-autoregression.html"><a href="arima100-eller-ar1-autoregression.html"><i class="fa fa-check"></i><b>10</b> ARIMA(1,0,0) eller AR(1) autoregression</a></li>
<li class="chapter" data-level="11" data-path="arima010-eller-i1-random-walk-with-a-drift.html"><a href="arima010-eller-i1-random-walk-with-a-drift.html"><i class="fa fa-check"></i><b>11</b> ARIMA(0,1,0) eller I(1) Random Walk with a drift</a></li>
<li class="chapter" data-level="12" data-path="arima001-eller-ma1-moving-average.html"><a href="arima001-eller-ma1-moving-average.html"><i class="fa fa-check"></i><b>12</b> ARIMA(0,0,1) eller MA(1) Moving average</a></li>
<li class="chapter" data-level="13" data-path="plots-med-forskellige-modeller.html"><a href="plots-med-forskellige-modeller.html"><i class="fa fa-check"></i><b>13</b> Plots med forskellige modeller</a></li>
<li class="chapter" data-level="14" data-path="arima-og-ssonalitet.html"><a href="arima-og-ssonalitet.html"><i class="fa fa-check"></i><b>14</b> ARIMA og sæsonalitet</a><ul>
<li class="chapter" data-level="14.1" data-path="arima-og-ssonalitet.html"><a href="arima-og-ssonalitet.html#traktorer"><i class="fa fa-check"></i><b>14.1</b> Traktorer</a></li>
<li class="chapter" data-level="14.2" data-path="arima-og-ssonalitet.html"><a href="arima-og-ssonalitet.html#detail-debet-card-forbrug-pa-island-millioner-isk."><i class="fa fa-check"></i><b>14.2</b> Detail debet card forbrug på Island (millioner ISK).</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="forecast-aktiekurser.html"><a href="forecast-aktiekurser.html"><i class="fa fa-check"></i><b>15</b> Forecast Aktiekurser</a></li>
<li class="divider"></li>
<li><a href="https://tepedu.com" target="blank">Thomas Petersen</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Kvantitative metoder for de finansielle uddannelser.</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="faktoranalyse" class="section level1">
<h1><span class="header-section-number">Kapitel 5</span> Faktoranalyse</h1>
<!-- http://yatani.jp/teaching/doku.php?id=hcistats:fa -->
<p>Faktoranalyse FA er ligesom, klyngeanalyse vi ser på senere, en strukturanalyse, der belyser hvilke sammenhænge der er i et datasæt. FA er en statistikmodel der navnlig bruges til at forenkle tolkningen af et datamateriale, der indeholder en stor mængde variable. FA bygger på et kæmpe antal udregninger med udgangspunkt i korrelationskoefficienter og er i praksis nærmest umulig at gennemføre uden brug af computersoftware. Før computerens opfindelse kunne en faktoranalyse nemt lægge beslag på en halv snes statistikere på fuld tid gennem flere måneder. Resultatet ville være identifikation få faktorer, skjult i et datamateriale.</p>
<p>Faktoranalysen kan fx. hjælpe med at vise sammenhænge mellem svar i spørgeskemaer, hvilket kan være en hjælp markedsføringsmæssigt, til at forstå hvilke svar samvarierer. En sådan gruppering af spørgsmål kan hjælpe med bedre at forstå kundernes ønsker og behov. Faktoranalyse FA er et godt værktøj til at forstå, hvad dine spørgeskemadata betyder, især når du har mange variable. Faktoranalysen forsøger at finde skjulte variable, som forklarer opførslen af dine observerede variable. FA har historiske rødder i psykometri, dvs målingen af mentale egenskaber.</p>
<p>I modsætning hertil søger man med Klyngeanalysen at finde sammenhænge mellem respondenterne/observationerne og altså ikke variablene, hvilket er et godt hjælpeværktøj i forbindelse med markedssegmentering.</p>
<p>Der findes 2 typer af FA Exploratory Factor Analysis (EFA) og Confirmatory Factor Analysis (CFA). EFA betyder, at du ikke rigtig ved, hvilke skjulte variable (eller faktorer) der findes, og hvor mange de er, så du forsøger at finde dem. CFA betyder, at du allerede har nogle gæt eller modeller på skjulte variable (eller faktorer), og vi vil kontrollere, om dette er korrekt. Vi benytter i det følgende EFA</p>
<div id="hvilke-faktorer-er-vigtige-nar-man-kber-en-ny-computer" class="section level2">
<h2><span class="header-section-number">5.1</span> Hvilke faktorer er vigtige når man køber en ny computer:</h2>
<p>Lad os sige, man har indsamlet et spørgeskema for at undersøge, hvad der er vigtigt, når en forbruger bestemmer, hvilken computer der skal købes. Spørgeskemaet er udformet, som hvor vigtig er Pris for computerkøbet, vægt fra 1 til 7 hvor 7 er højest/vigtigst.</p>
<p>Dette datasæt er lille i forhold til, hvad der er realistisk, da vi blot forsøger at illustrere analysen. Normalt vil man have flere end 6 variable. For at sikre solid analyseresultater vil man have flere respondenter/observationer.</p>
<p>I noterne er input til R og output fra R, markeret i grå rammer. Output dvs. resultaterne R leverer er markeret med ## i hver linje. Input dvs. de kommandoer vi skal skrive ind i R er ikke markeret.</p>
<p>Rammen herunder er input til R, da linjerne ikke er markeret. Læs datasættet ind i R, dette kan du gøre ved at copy paste nedenstående kode, i den grå ramme, direkte ind i R enten i console eller et script.</p>
<p>Bemærk data.frame er en to-dimensionel data struktur, nedenstående betyder vore 6 variable nu er lagret i en dataframe.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1">Pris &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2">Software &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">7</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">3</span>)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3">Æstetik &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">7</span>)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4">Brand &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">7</span>)</a>
<a class="sourceLine" id="cb1-5" data-line-number="5">Venner &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">7</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">7</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>)</a>
<a class="sourceLine" id="cb1-6" data-line-number="6">Familie &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>)</a>
<a class="sourceLine" id="cb1-7" data-line-number="7"></a>
<a class="sourceLine" id="cb1-8" data-line-number="8">data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(Pris, Software, Æstetik, Brand, Venner, Familie)</a></code></pre></div>
</div>
<div id="forudstninger-for-faktoranalysen." class="section level2">
<h2><span class="header-section-number">5.2</span> Forudsætninger for faktoranalysen.</h2>
<p>Nu skal vi undersøge om det er fornuftigt at foretage en faktoranalyse, dette kan vi undersøge ved enten Bartletts korrelationstest eller Kaiser-Meyer-Olkin KMO.</p>
<p>For at teste dette skal man installere og loade pakken psych, vi skal kun installere første gang. Bemærk install.packages(“psych”) er kommenteret ud nedenfor, så første gang skal du kommentere install.packages(“psych”) ud.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="co">#install.packages(&quot;psych&quot;)</span></a>
<a class="sourceLine" id="cb2-2" data-line-number="2"><span class="kw">library</span>(<span class="st">&quot;psych&quot;</span>)</a></code></pre></div>
<p>Du kan alternativt benytte pacman pakken, hvilket ofte er at foretrække. Hvis du indlæser nedenstående installeres og loades pakken psych:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="cf">if</span> (<span class="op">!</span><span class="kw">require</span>(<span class="st">&quot;pacman&quot;</span>)) <span class="kw">install.packages</span>(<span class="st">&quot;pacman&quot;</span>)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2">pacman<span class="op">::</span><span class="kw">p_load</span>(psych)</a></code></pre></div>
<p>Nu hvor psych pakken er indlæst kan vi køre bartlett test i R:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw">cortest.bartlett</span>(data)</a></code></pre></div>
<pre><code>## $chisq
## [1] 36.15696
## 
## $p.value
## [1] 0.00167791
## 
## $df
## [1] 15</code></pre>
<p>Nulhypotesen i Bartletts test er at variablene ikke er korrelerede dvs. alle korrelationskoefficienter <span class="math inline">\(\rho=0\)</span>,</p>
<p><span class="math display">\[H_0:Alle\ \rho=0\]</span>
<span class="math display">\[H_1:Ikke\ alle\ \rho=0  \]</span></p>
<p>Forkaster vi nulhypotesen, er der basis for at gennemføre faktoranalysen. Den lille p-værdi på 0.00167791, betyder vi gennemfører faktoranalysen.</p>
<p>Vi kan ligeledes køre Kaiser-Meyer-Olkin KMO testet fra pshych pakken:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">KMO</span>(data)</a></code></pre></div>
<pre><code>## Kaiser-Meyer-Olkin factor adequacy
## Call: KMO(r = data)
## Overall MSA =  0.49
## MSA for each item = 
##     Pris Software  Æstetik    Brand   Venner  Familie 
##     0.71     0.70     0.57     0.49     0.30     0.37</code></pre>
<p>For KMO skal Overall MSA = 0.49, fortæller om egnethed af data til faktoranalyse. Skal være større end kritisk grænse på ca. 0.5, dette er ikke helt tilfældet her, men vi gennemfører alligevel faktoranalysen.</p>
<p>Vi kan se af korrelationsmatricen, at nogle variable er korrellerede og andre tilsyneladende ikke.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">cor</span>(data)</a></code></pre></div>
<pre><code>##                 Pris   Software     Æstetik       Brand     Venner
## Pris      1.00000000  0.1856123 -0.63202219 -0.58026680 0.03082006
## Software  0.18561230  1.0000000 -0.14621516 -0.11858645 0.10096774
## Æstetik  -0.63202219 -0.1462152  1.00000000  0.85285436 0.03989799
## Brand    -0.58026680 -0.1185864  0.85285436  1.00000000 0.33316719
## Venner    0.03082006  0.1009677  0.03989799  0.33316719 1.00000000
## Familie  -0.06183118  0.1765724 -0.06977360  0.02662389 0.60727189
##              Familie
## Pris     -0.06183118
## Software  0.17657236
## Æstetik  -0.06977360
## Brand     0.02662389
## Venner    0.60727189
## Familie   1.00000000</code></pre>
<p>Så det ser ud til, at Pris har stærke negative sammenhænge med Æstetik og Brand.<br />
Venner har en stærk positiv sammenhæng med Familie.</p>
<p>Det betyder, at vi kan forvente, at vi vil have to fælles faktorer, og en vil være relateret til pris, æstetik og brand, og den anden vil være relateret til ven og familie. Vi kan lave et corrplot, der grafisk illustrerer disse sammenhænge, store blå prikker er positiv korrelation, store røde negativ korrelation. Så vi skal installere corplott pakken, her bruger vi pacman til installationen.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">pacman<span class="op">::</span><span class="kw">p_load</span>(corrplot)</a>
<a class="sourceLine" id="cb10-2" data-line-number="2"><span class="kw">corrplot</span>(<span class="kw">cor</span>(data), <span class="dt">order =</span> <span class="st">&quot;hclust&quot;</span>, <span class="dt">tl.col=</span><span class="st">&#39;black&#39;</span>, <span class="dt">tl.cex=</span>.<span class="dv">5</span>) </a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/corrplot-1.svg" width="672" /></p>
</div>
<div id="selve-faktoranalysen" class="section level2">
<h2><span class="header-section-number">5.3</span> Selve Faktoranalysen</h2>
<p>Vi er nu klar til at teste om der er grundlag for at sammenlægge variable til faktorer. Dette tester vi i selve faktor analysen, ved hjælp af funktionen factanal.</p>
<p>Hvis vi samler alle spørgsmål til en samlet faktor, har vi følgende faktor analyse:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">fa1 &lt;-<span class="st"> </span><span class="kw">factanal</span>(data, <span class="dt">factor=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb11-2" data-line-number="2">fa1</a></code></pre></div>
<pre><code>## 
## Call:
## factanal(x = data, factors = 1)
## 
## Uniquenesses:
##     Pris Software  Æstetik    Brand   Venner  Familie 
##    0.567    0.977    0.126    0.167    0.974    1.000 
## 
## Loadings:
##          Factor1
## Pris     -0.658 
## Software -0.152 
## Æstetik   0.935 
## Brand     0.912 
## Venner    0.161 
## Familie         
## 
##                Factor1
## SS loadings      2.190
## Proportion Var   0.365
## 
## Test of the hypothesis that 1 factor is sufficient.
## The chi square statistic is 12.79 on 9 degrees of freedom.
## The p-value is 0.172</code></pre>
<p><strong>Uniqueness</strong> angiver hvor meget af variationen i en variabel, der ikke er associeret med faktoren. Jo lavere Uniqueness, des større sammenhæng til faktorerne.</p>
<p><strong>Loadings</strong> angiver hvordan hver variabel er vægtet for faktorerne, men også hvor stærk korrelationen er til hver faktor. Faktor 1 påvirkes således mest af Æstetik, Brand og Pris. Denne faktor kan ses af corrplottet hvor disse tre variable ses at påvirke hinanden, Pris er negativt korreleret med Æstetik og Brand.</p>
<p><strong>Proportion Var</strong> er et vigtigt nøgletal, der angiver andelen af variationen i data, der er forklaret af den pågældende faktor. Her forklares alså kun 36.5% af variationen i datasættet. Proportion Var findes som SS loadings divideret med antallet af variable dvs. her 6.</p>
<p>Lad os se på hvad der sker, hvis vi deler variablene op i 2 faktorer:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">fa2 &lt;-<span class="st"> </span><span class="kw">factanal</span>(data, <span class="dt">factor=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb13-2" data-line-number="2">fa2</a></code></pre></div>
<pre><code>## 
## Call:
## factanal(x = data, factors = 2)
## 
## Uniquenesses:
##     Pris Software  Æstetik    Brand   Venner  Familie 
##    0.559    0.960    0.126    0.080    0.005    0.609 
## 
## Loadings:
##          Factor1 Factor2
## Pris     -0.657         
## Software -0.161   0.119 
## Æstetik   0.933         
## Brand     0.928   0.242 
## Venner    0.100   0.992 
## Familie           0.620 
## 
##                Factor1 Factor2
## SS loadings      2.207   1.453
## Proportion Var   0.368   0.242
## Cumulative Var   0.368   0.610
## 
## Test of the hypothesis that 2 factors are sufficient.
## The chi square statistic is 2.16 on 4 degrees of freedom.
## The p-value is 0.706</code></pre>
<p><strong>Cumulative Var</strong> 0.61 er summen af proportion var 0.368 og 0.242, og betyder at faktor 1 og faktor 2 forklarer 61% af variationen i datamaterialet.</p>
<p>Faktor 2 forklares altså primært af Venner og Familie, dette stemmer godt overens med billedet vi så i corrplot.</p>
<p>Nu opdeler vi variablene i 3 faktorer.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">fa3 &lt;-<span class="st"> </span><span class="kw">factanal</span>(data, <span class="dt">factor=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb15-2" data-line-number="2">fa3</a></code></pre></div>
<pre><code>## 
## Call:
## factanal(x = data, factors = 3)
## 
## Uniquenesses:
##     Pris Software  Æstetik    Brand   Venner  Familie 
##    0.468    0.944    0.154    0.005    0.193    0.005 
## 
## Loadings:
##          Factor1 Factor2 Factor3
## Pris     -0.717           0.122 
## Software -0.146   0.172         
## Æstetik   0.908  -0.130         
## Brand     0.892  -0.116   0.430 
## Venner            0.440   0.781 
## Familie           0.970   0.228 
## 
##                Factor1 Factor2 Factor3
## SS loadings      2.161   1.198   0.872
## Proportion Var   0.360   0.200   0.145
## Cumulative Var   0.360   0.560   0.705
## 
## The degrees of freedom for the model is 0 and the fit was 0.0188</code></pre>
<p>Nu forklares 70.5% af variationen i datamaterialet altså ud fra de 3 faktorer.</p>
</div>
<div id="hvor-mange-faktorer-br-benyttes" class="section level2">
<h2><span class="header-section-number">5.4</span> Hvor mange faktorer bør benyttes?</h2>
<p>Der er ingen fast regel for hvor mange faktorer der bør benyttes. Der er flere forskelle metoder til bestemmelse af antallet af faktorer, vi viser herunder 2 metoder.</p>
<div id="eigenvalues-metoden" class="section level3">
<h3><span class="header-section-number">5.4.1</span> Eigenvalues metoden</h3>
<p>Eigenvalues udtrykker hvor meget af datamaterialets samlede varians, der dækkes af den pågældende faktor. Eigenvalues er standardiserede således at summen giver antallet af variable, herunder ses at summen er 6, da der er 6 variable i datasættet. Vi ser hvor stor en del af variationen hver faktor forklarer, når der er 6 faktorer. Faktor 5 og faktor 6 bibringer meget lidt yderligere forklaring af variationen.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">ev &lt;-<span class="st"> </span><span class="kw">eigen</span>(<span class="kw">cor</span>(data))</a>
<a class="sourceLine" id="cb17-2" data-line-number="2">ev<span class="op">$</span>values</a></code></pre></div>
<pre><code>## [1] 2.45701130 1.68900056 0.89157047 0.60583326 0.27285334 0.08373107</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">sum</span>(ev<span class="op">$</span>values)</a></code></pre></div>
<pre><code>## [1] 6</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">ev<span class="op">$</span>values<span class="op">/</span><span class="kw">sum</span>(ev<span class="op">$</span>values)</a></code></pre></div>
<pre><code>## [1] 0.40950188 0.28150009 0.14859508 0.10097221 0.04547556 0.01395518</code></pre>
<p>Når vi benytter Eigenvalues metoden, bestemmes antallet af faktorer ud fra antallet af Eigenvalues større end 1, det er denne metode fx. SPSS benytter. Vi ser at kun 2 Eigenvalues er 2.45701130 og 1.68900056 er større end 1, vi får således kun 2 faktorer. Eigenvalues metoden er ofte lidt konservativ, således at vi får færre faktorer end med de øvrige metoder.</p>
</div>
<div id="screeplot-metoden" class="section level3">
<h3><span class="header-section-number">5.4.2</span> Screeplot metoden</h3>
<p>Vi kan se på nedenstående screeplot, der hvor kurven flader ud, bibringer yderligere faktorer ikke synderlig megen yderligere forklaring til modellen. Man vil med screeplot kriteriet, vælge antallet af faktorer hvor kurven knækkker i tilfældet med 3 faktorer. Man vil ikke altid entydigt kunne afgøre hvor screeplot kurven knækker, her må man så afgøre dette bedst muligt.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">screeplot</span>(<span class="kw">princomp</span>(data),<span class="dt">type=</span><span class="st">&quot;line&quot;</span>,<span class="dt">npcs =</span> <span class="dv">6</span>, <span class="dt">main=</span><span class="st">&quot;Screeplot Computereksempel&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-14-1.svg" width="672" /></p>
<br>
<details>
<p><summary>Spørgsmål personality Stanford</summary>
Hent nu filen personality, hvor 240 Stanford studerende har svaret på i hvor høj grad de mener at besidde 32 forskellige personlighedstræk. 1 til 8 hvor 1 er mindst og 8 er mest. Foretag hvis en test viser dette er fordelagtigt en faktoranalyse.</p>
<p>Download personality fra filen <a href="personality.xlsx" download>her</a> og importer den i R via File - Import Dataset.</p>
</details>
<br>
<details>
<p><summary>Svar personality Stanford</summary>
Løsning med video bliver lagt op senere.</p>
<!-- ```{r echo=FALSE, warning=FALSE} -->
<!-- library(readxl) -->
<!-- personality <- read_excel("personality.xlsx") -->
<!-- ``` -->
<!-- ```{r} -->
<!-- library("psych") -->
<!-- cortest.bartlett(personality) -->
<!-- KMO(personality) -->
<!-- ``` -->
<!-- Vi gennemfører klart analysen viser begge tests. -->
<!-- ```{r, dev='svg'} -->
<!-- #cor(personality) korrelationsmatricen er udeladt af pladshensyn. -->
<!-- corrplot(cor(personality), order = "hclust", tl.col='black', tl.cex=.5)  -->
<!-- ``` -->
<!-- ```{r, dev='svg'} -->
<!-- screeplot(princomp(personality),type="line", main="Screeplot personality") -->
<!-- ``` -->
<!-- ```{r} -->
<!-- evp <- eigen(cor(personality)) -->
<!-- evp$values -->
<!-- ``` -->
<!-- Vi benytter 8 faktorer -->
<!-- ```{r} -->
<!-- fapers8 <- factanal(personality,8) -->
<!-- ``` -->
</details>
<br>
<details>
<p><summary>Spørgsmål Mediedata</summary></p>
<p>Download filen om mediedata <a href="mediedata.xlsx" download>her</a>. Importer denne i R, husk under importen at vælge det korrekte sheet, der indeholder data.</p>
<p>Datasættet omhandler danskernes medievaner, 324 danskere er blevet spurgt om deres medievaner. Datasættet indeholder følgende 11 variable.</p>
<p><strong>TV-kigning</strong><br />
samlet Antal minutter pr. dag.</p>
<p><strong>Radiolytning</strong><br />
Samlet Antal minutter pr. dag.</p>
<p><strong>Avislæsning</strong><br />
Samlet Antal minutter pr. dag.</p>
<p><strong>TV-kigning</strong><br />
Nyheder Antal minutter pr. dag. “Nyheder” omfatter “Nyheder, politik og aktuelt”</p>
<p><strong>Radiolytning</strong><br />
Nyheder Antal minutter pr. dag. “Nyheder” omfatter “Nyheder, politik og aktuelt”</p>
<p><strong>Avislæsning</strong><br />
Nyheder Antal minutter pr. dag. “Nyheder” omfatter “Nyheder, politik og aktuelt”</p>
<p><strong>Internetforbrug</strong><br />
0 Ingen internetadgang hjemme eller på arbejde<br />
1 Bruger aldrig<br />
2 Mindre end en gang om måneden<br />
3 En gang om måneden<br />
4 Flere gange om måneden<br />
5 En gang om ugen<br />
6 Flere gange om ugen<br />
7 Hver dag</p>
<p><strong>Alder</strong><br />
Alder i år</p>
<p><strong>Højest fuldførte uddannelse </strong><br />
1 Folkeskole 6.-8. klasse<br />
2 Folkeskole 9.-10. klasse<br />
3 Gymnasielle uddannelser, studentereksamen, HF, HHX, HTX<br />
4 Kort erhvervsudd. under 1-2 års varighed, F.eks AMU Arbejdsmarkedsudd., Basisår Erhvervsfaglige udd.<br />
5 Faglig udd. (håndværk, handel, landbrug mv.), F.eks. Faglærte, Social- og sundhedsassistent-udd. og tilsvarende<br />
6 Kort videreg. udd af op til 2-3 år, F.eks. Erhv.akademi, datamatiker, tandplejer, byggetekniker, installatør, HD<br />
7 Mellemlang videreg.udd. 3-4 år. Prof.bachelorer, F.eks. Diploming, sygeplejerske, skolelærer, pædagog, journalist, HA<br />
8 Universitetsbachelor. 1. del af kandidatuddannelse
9 Lang videregående uddannelse. Kandidatuddannelser af 5.-6. års varighed, F.eks. Cand.mag., cand.jur., cand.polyt. etc.<br />
10 Forskeruddannelse. Ph.d., doktor</p>
<p><strong>Kvindedummy</strong><br />
Dummy variabel kodet med kvinde=1, mand=0</p>
<p><strong>Hjemmeboendebørndummy</strong><br />
Dummy variabel kodet med Ja=1, Nej=0</p>
<p>Gennemfør en faktor analyse på datasættet.</p>
</details>
<br>
<details>
<p><summary>Spørgsmål Genderroles</summary></p>
<p>Download filen genderroles <a href="genderroles.xlsx" download>her</a> og importer den i R via File - Import Dataset.
Pas på variablene skal konverteres til dummy variable hvor det giver mening, man kan ændre variablen Region til et passende antal dummy variable.</p>
<p>Gennemfør en faktor analyse på datasættet.</p>
</details>
<p><br></p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cran-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="klyngeanalyse.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
